// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrganizingEventsService.Infrastructure.Persistence.Contexts;

#nullable disable

namespace OrganizingEventsService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "event_participant_invite_status", new[] { "accepted", "declined", "pending" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "event_status", new[] { "in_draft", "planed", "is_over", "in_going" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("email");

                    b.Property<bool?>("IsInvite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_invite")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("account_pkey");

                    b.HasIndex(new[] { "Email" }, "account_email_key")
                        .IsUnique();

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDatetime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_datetime");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("invite_code");

                    b.Property<decimal>("MaxParticipant")
                        .HasPrecision(4)
                        .HasColumnType("numeric(4)")
                        .HasColumnName("max_participant");

                    b.Property<string>("MeetingLink")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("meeting_link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("StartDatetime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("InDraft")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("event_pkey");

                    b.HasIndex(new[] { "InviteCode" }, "event_invite_code_key")
                        .IsUnique();

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountPk")
                        .HasColumnType("uuid")
                        .HasColumnName("account_pk");

                    b.Property<Guid>("EventPk")
                        .HasColumnType("uuid")
                        .HasColumnName("event_pk");

                    b.Property<string>("InviteStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invite_status");

                    b.Property<bool?>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned")
                        .HasDefaultValueSql("false");

                    b.Property<Guid>("RolePk")
                        .HasColumnType("uuid")
                        .HasColumnName("role_pk");

                    b.HasKey("Id")
                        .HasName("event_participant_pkey");

                    b.HasIndex("AccountPk");

                    b.HasIndex("EventPk");

                    b.HasIndex("RolePk");

                    b.ToTable("event_participant", (string)null);
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventParticipantPk")
                        .HasColumnType("uuid")
                        .HasColumnName("event_participant_pk");

                    b.Property<decimal>("Rating")
                        .HasPrecision(1)
                        .HasColumnType("numeric(1)")
                        .HasColumnName("rating");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("feedback_pkey");

                    b.HasIndex("EventParticipantPk");

                    b.ToTable("feedback", (string)null);
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("permission_pkey");

                    b.HasIndex(new[] { "Name" }, "permission_name_key")
                        .IsUnique();

                    b.ToTable("permission", (string)null);
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("role_pkey");

                    b.HasIndex(new[] { "Name" }, "role_name_key")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PermissionPk")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_pk");

                    b.Property<Guid>("RolePk")
                        .HasColumnType("uuid")
                        .HasColumnName("role_pk");

                    b.HasKey("Id")
                        .HasName("role_permission_pkey");

                    b.HasIndex("PermissionPk");

                    b.HasIndex("RolePk");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.EventParticipant", b =>
                {
                    b.HasOne("OrganizingEventsService.Infrastructure.Persistence.Entities.Account", "AccountPkNavigation")
                        .WithMany("EventParticipants")
                        .HasForeignKey("AccountPk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("event_participant_account_pk_fkey");

                    b.HasOne("OrganizingEventsService.Infrastructure.Persistence.Entities.Event", "EventPkNavigation")
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventPk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("event_participant_event_pk_fkey");

                    b.HasOne("OrganizingEventsService.Infrastructure.Persistence.Entities.Role", "RolePkNavigation")
                        .WithMany("EventParticipants")
                        .HasForeignKey("RolePk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("event_participant_role_pk_fkey");

                    b.Navigation("AccountPkNavigation");

                    b.Navigation("EventPkNavigation");

                    b.Navigation("RolePkNavigation");
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.Feedback", b =>
                {
                    b.HasOne("OrganizingEventsService.Infrastructure.Persistence.Entities.EventParticipant", "EventParticipantPkNavigation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("EventParticipantPk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("feedback_event_participant_pk_fkey");

                    b.Navigation("EventParticipantPkNavigation");
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.RolePermission", b =>
                {
                    b.HasOne("OrganizingEventsService.Infrastructure.Persistence.Entities.Permission", "PermissionPkNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionPk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permission_permission_pk_fkey");

                    b.HasOne("OrganizingEventsService.Infrastructure.Persistence.Entities.Role", "RolePkNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RolePk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permission_role_pk_fkey");

                    b.Navigation("PermissionPkNavigation");

                    b.Navigation("RolePkNavigation");
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.Account", b =>
                {
                    b.Navigation("EventParticipants");
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.Event", b =>
                {
                    b.Navigation("EventParticipants");
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.EventParticipant", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("OrganizingEventsService.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Navigation("EventParticipants");

                    b.Navigation("RolePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
